name: Nebraska POTA Tracker

permissions:
  contents: write

on:
  schedule:
    - cron: "0 23 * * *"   # runs daily at 14:00 UTC (~9 AM Nebraska)
  workflow_dispatch:       # allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Download repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python pota_tracker_2.py
          
      - name: Commit updated park snapshots
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "pota-bot"
          git config --global user.email "actions@github.com"
          git add pota_data
          git commit -m "Update park snapshots" || echo "No changes"
          git push https://$GH_PAT@github.com/mattvancleave-mvc/pota-ne-tracker.git
